import React, { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import MobileLayout from '@/Layouts/MobileLayout';
import { FaArrowRight, FaCalendarAlt, FaPlus, FaSearch } from 'react-icons/fa';

const statusColors = { todo: 'bg-slate-100 text-slate-600', in_progress: 'bg-amber-100 text-amber-700', done: 'bg-emerald-100 text-emerald-700', en_attente: 'bg-blue-100 text-blue-700' };

export default function MobileTasksIndex({ tasks: taskProp = { data: [] }, filters = {}, summary = {} }) {
	const tasks = Array.isArray(taskProp) ? taskProp : taskProp.data || [];
	const [search, setSearch] = useState(filters.search || '');
	const submitSearch = (event) => { event.preventDefault(); router.get('/tasks', { ...filters, search }, { preserveState: true, replace: true }); };
	return <MobileLayout title="Taches" fullBleed><Head title="Taches" /><div className="min-h-full bg-slate-50 px-4 pb-5 pt-4 dark:bg-slate-950"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-blue-600">A faire aujourd'hui</p><h2 className="mt-1 text-2xl font-bold text-slate-950 dark:text-white">Mes taches</h2></div><Link href="/tasks/create" className="flex h-11 w-11 items-center justify-center rounded-full bg-blue-600 text-white shadow-lg shadow-blue-600/25 active:scale-95" aria-label="Nouvelle tache"><FaPlus /></Link></div><form onSubmit={submitSearch} className="relative mb-5"><FaSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Rechercher une tache" className="h-12 w-full rounded-2xl border-0 bg-white pl-11 pr-4 text-sm shadow-sm ring-1 ring-slate-200 focus:ring-2 focus:ring-blue-500 dark:bg-slate-900 dark:ring-slate-800" /></form><div className="mb-5 flex gap-2 overflow-x-auto"><div className="min-w-[92px] rounded-2xl bg-blue-600 p-3 text-white"><p className="text-xl font-bold">{summary.total || tasks.length}</p><p className="text-[11px] text-blue-100">Total</p></div><div className="min-w-[92px] rounded-2xl bg-white p-3 shadow-sm dark:bg-slate-900"><p className="text-xl font-bold text-slate-950 dark:text-white">{summary.in_progress || 0}</p><p className="text-[11px] text-slate-500">En cours</p></div><div className="min-w-[92px] rounded-2xl bg-white p-3 shadow-sm dark:bg-slate-900"><p className="text-xl font-bold text-slate-950 dark:text-white">{summary.done || 0}</p><p className="text-[11px] text-slate-500">Terminees</p></div></div><div className="space-y-3">{tasks.map((task) => <Link key={task.id} href={`/tasks/${task.id}`} className="block rounded-2xl border border-slate-200 bg-white p-4 shadow-sm active:scale-[.99] dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="text-sm font-bold text-slate-950 dark:text-white">{task.title}</h3><p className="mt-1 truncate text-xs text-slate-500">{task.project?.name || task.project_name || 'Sans projet'}</p></div><FaArrowRight className="mt-1 flex-shrink-0 text-xs text-slate-400" /></div><div className="mt-4 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusColors[task.status] || statusColors.todo}`}>{task.status || 'A faire'}</span>{task.due_date && <span className="flex items-center gap-1 text-xs text-slate-400"><FaCalendarAlt />{new Date(task.due_date).toLocaleDateString('fr-FR')}</span>}</div></Link>)}{!tasks.length && <div className="rounded-2xl bg-white p-8 text-center text-sm text-slate-500 dark:bg-slate-900">Aucune tache trouvee.</div>}</div></div></MobileLayout>;
}
